import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import "aladin-lite-react/dist/aladin.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "SPHEREx HiPS Channel Maps",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
